apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::130551533951:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JZKGUSAYOBGF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::130551533951:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T17:22:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1609"
  uid: a82d6ecb-b24c-4853-961a-b53eee4b83a8
